config/routes.rb
ValidationProto::Application.routes.draw do
  resources :oranges

end

app/models/orange.rb
class Orange < ActiveRecord::Base

  validates :blueberry, :presence => {:message=>'My custom message'}
  validates :cherry, :numericality => true, :uniqueness => true  
  validates :latitude, 
    :presence => {:message => "is required"}, 
    :format => { :with => /^(-?(90|([0-8]?\d))((\.|,)\d{1,5})?)?$/, 
    :message => "must be between -90.0 and 90.0" 
  }
  
  validates :longitude, 
    :presence => {:message => "is required"}, 
    :format => { :with => /^(-?(180|((1[0-7]|\d?)\d))((\.|,)\d{1,5})?)?$/, 
    :message => "must be between -180.0 and 180.0" 
  }

  def latitude=(value)
    logger.info "value = " + value.to_s   
    logger.info "value.class = " + value.class.to_s 
    write_attribute :latitude, value.gsub(',','.')
    latitude
  end

  def longitude=(value)
    write_attribute :longitude, value.gsub(',','.')
    longitude
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/oranges_controller.rb
class OrangesController < ApplicationController
  # GET /oranges
  # GET /oranges.xml
  def index
    @oranges = Orange.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @oranges }
    end
  end

  # GET /oranges/1
  # GET /oranges/1.xml
  def show
    @orange = Orange.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @orange }
    end
  end

  # GET /oranges/new
  # GET /oranges/new.xml
  def new
    @orange = Orange.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @orange }
    end
  end

  # GET /oranges/1/edit
  def edit
    @orange = Orange.find(params[:id])
  end

  # POST /oranges
  # POST /oranges.xml
  def create
    @orange = Orange.new(params[:orange])

    respond_to do |format|
      if @orange.save
        format.html { redirect_to(@orange, :notice => 'Orange was successfully created.') }
        format.xml  { render :xml => @orange, :status => :created, :location => @orange }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @orange.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /oranges/1
  # PUT /oranges/1.xml
  def update
    @orange = Orange.find(params[:id])

    respond_to do |format|
      if @orange.update_attributes(params[:orange])
        format.html { redirect_to(@orange, :notice => 'Orange was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @orange.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /oranges/1
  # DELETE /oranges/1.xml
  def destroy
    @orange = Orange.find(params[:id])
    @orange.destroy

    respond_to do |format|
      format.html { redirect_to(oranges_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oranges_helper.rb
module OrangesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ValidationProto</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery', 'client-side-validations'-%>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/oranges/_form.html.erb
<%= form_for(@orange, :validate => true) do |f| %>
  <% if @orange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orange.errors.count, "error") %> prohibited this orange from being saved:</h2>

      <ul>
      <% @orange.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blueberry %><br />
    <%= f.text_field :blueberry, :placeholder => ":presence => true" %>
  </div>
  <div class="field">
    <%= f.label :cherry %><br />
    <%= f.text_field :cherry,  :placeholder => ":numericality => true" %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude,  :placeholder => "latitude include point of ','" %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude,  :placeholder => "longitude including point of ','" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/oranges/edit.html.erb
<h1>Editing orange</h1>

<%= render 'form' %>

<%= link_to 'Show', @orange %> |
<%= link_to 'Back', oranges_path %>

app/views/oranges/index.html.erb
<h1>Listing oranges</h1>

<table>
  <tr>
    <th>Blueberry</th>
    <th>Cherry</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @oranges.each do |orange| %>
  <tr>
    <td><%= orange.blueberry %></td>
    <td><%= orange.cherry %></td>
    <td><%= link_to 'Show', orange %></td>
    <td><%= link_to 'Edit', edit_orange_path(orange) %></td>
    <td><%= link_to 'Destroy', orange, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Orange', new_orange_path %>

app/views/oranges/new.html.erb
<h1>New orange</h1>

<%= render 'form' %>

<%= link_to 'Back', oranges_path %>

app/views/oranges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Blueberry:</b>
  <%= @orange.blueberry %>
</p>

<p>
  <b>Cherry:</b>
  <%= @orange.cherry %>
</p>

<p>
  <b>Latitude:</b>
  <%= @orange.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @orange.longitude %>
</p>


<%= link_to 'Edit', edit_orange_path(@orange) %> |
<%= link_to 'Back', oranges_path %>